language: c

compiler:
    - gcc

git:
  depth: 1

env: CTEST_OUTPUT_ON_FAILURE=1

install:
    - sudo pip install cpp-coveralls
    - sudo apt-get update -qq
    - sudo apt-get install -qq cmake python3-minimal

script:
    - cmake . -DCMAKE_C_FLAGS='-O0 --coverage' -DCMAKE_CXX_FLAGS='-O0 --coverage'
    - make
    - make test

after_success:
    - coveralls --exclude-pattern '.*CMake[^/]+\.c(?:pp)?'

notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/d4ac611092a6de1b9db4
        on_success: change  # options: [always|never|change] default: always
        on_failure: always  # options: [always|never|change] default: always
        on_start: false     # default: false

    slack:
        secure: c0AYxCRD90MWMEcrxWjnWxEeX4f5aIAJbcg8+07oOYwxTsIKITNG3xiKlTPbJuw8eePRUHysIkmF4EuDM4etasQMYUAtgGlOHaH8eTwFRMI2MAmU0gwOlb0wD1tKOi6YaN7ZF/XukZLytk2pZ55u4mNcBhqvHbjR0w66n0aYDo0=
